# lab.conf - Kathara Topology Definition

# Connect interface 0 of each device to the 'A' collision domain
h1[0] = A
h2[0] = A
attacker[0] = A

# Enable bridged networking (internet access for setup) for the attacker and server
# This allows 'apt-get' to fetch packages using the host's NAT connection
h2[bridged]=yes
attacker[bridged]=yes

# Suppress ICMP Redirect Message on Attacker Machine 
# Otherwise attacker's own machine would flag traffic coming and going from same intf as suspicious
# send ICMP redirect

attacker[sysctl]="net.ipv4.conf.eth0.send_redirections=0"
attacker[sysctl]="net.ipv4.conf.all.send_redirections=0"

# sysctl is a linux tool to modify/read kernel parameters at runtime